## Extracting latest news of bajar ko chirfaar

In [17]:
https://bajarkochirfar.com/latest/


# /html/body/div[1]/header/div[2]/button[1]  : click 



# /html/body/div[1]/section/div/div[2]/div[4]/article/a[2]



# /html/body/div[1]/div[1]/div/div[1]/main/div/div[1]/article/div 

# title

SyntaxError: invalid syntax (1086418570.py, line 1)

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
from datetime import datetime
import pandas as pd
import os
import json

# 1. Initialize the Chrome WebDriver instance
driver = webdriver.Chrome()

driver.get("https://bajarkochirfar.com/latest/")
print(f"Page Title: {driver.title}")


driver.execute_script("window.scrollBy(0, 1000);")

time.sleep(5)

driver.find_element(By.XPATH,"/html/body/div[1]/header/div[2]/button[1]").click()

time.sleep(5)
url_links=[]

for i in range(1,6):
    try:
        url=driver.find_element(By.XPATH,f"/html/body/div[1]/section/div/div[2]/div[{i}]/article/a[2]").get_attribute("href")
        url_links.append(url)
        # print(url)
    except:
        print("pass")

# /html/body/div[1]/div[1]/div/div[1]/main/div/div[1]/article/div
news={}
for url in url_links:
    driver.get(url)
    time.sleep(5)
    news[driver.title]=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/div/div[1]/main/div/div[1]/article/div").text
    
now = datetime.now()

# safe filename (remove spaces + colons)
news_time = now.strftime("%Y-%m-%d_%H-%M-%S")

# dataframe
df = pd.DataFrame(list(news.items()), columns=["title", "news"])

# folder path
folder = r"C:\Users\HP\Desktop\data_extractions\New folder\latest_news"
os.makedirs(folder, exist_ok=True)

csv_path = os.path.join(folder, f"{news_time}.csv")

df.to_csv(
    csv_path,
    index=False,
    encoding="utf-8-sig"
)


json_path = os.path.join(folder, f"{news_time}.json")

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(
        df.to_dict(orient="records"),
        f,
        ensure_ascii=False,
        indent=4
    )

driver.quit()

Page Title:
pass

In [ ]:
 list(news.keys())[0]

In [ ]:
news[ list(news.keys())[0]]

In [2]:
df

,title,news
0,तातो लहरसम्बन्धी विशेष बुलेटिनः यी १४ जिल्लामा...,जल तथा मौसम विज्ञान विभागले तातो दिन वा तातो ल...
1,रवि लामिछाने भारत भ्रमण सकेर आज स्वदेश फर्किँद...,राष्ट्रिय स्वतन्त्र पार्टी (रास्वपा) का सभापति...
2,सर्वसाधारणले जेठ २९ गतेदेखि प्रतिकित्ता १०० रु...,यूनाइटेड अजोड इन्स्योरेन्स लिमिटेडले हकप्रद से...
3,सरकारले सार्वजनिक गर्यो पशुपति सहकारीका ऋणीको ...,सरकारले समस्याग्रस्त घोषित पशुपति सेभिङ एण्ड क...

In [ ]:
# /html/body/div[1]/section/div/div[2]/div[5]/article/a[2]
# /html/body/div[1]/section/div/div[2]/div[6]/article/a[2]



# /html/body/div[1]/section/div/div[2]/div[2]/article/a[2]
# /html/body/div[1]/section/div/div[2]/div[3]/article/a[2]
# /html/body/div[1]/section/div/div[2]/div[4]/article/a[2]

In [22]:
df = pd.DataFrame(list(news.items()), columns=["title", "news"])
df

,title,news
0,चिकित्सक लाइसेन्स परीक्षामा स्वदेशी कलेज अग्रस...,यसवर्ष नेपाल मेडिकल काउन्सिल (एनएमसी) ले सार्व...
1,कोरला नाकाबाट भित्रिएका ७७४ विद्युतीय गाडी भन्...,सशस्त्र प्रहरी बल नेपालले भन्सार छलेको आशङ्काम...
2,प्रधानमन्त्रीको प्रचारपछि बढ्यो डीडीसी उत्पादन...,सरकारी स्वामित्वको दुग्ध विकास संस्थान (डीडीसी...
3,"नेपालको पासपोर्ट र्याङ्किङमा सुधार, कति औं स्थ...",नेपालले हेन्ली पासपोर्ट इन्डेक्स–२०२६ मा चार स...

In [21]:
news.

{'चिकित्सक लाइसेन्स परीक्षामा स्वदेशी कलेज अग्रस्थानमा | BAJARKO CHIRFAR': 'यसवर्ष नेपाल मेडिकल काउन्सिल (एनएमसी) ले सार्वजनिक गरेको लाइसेन्स) परीक्षाको नतिजामा ६६ दशमलव ९५ प्रतिशत विद्यार्थी उत्तीर्ण भएका छन् ।\n नेपाल मेडिकल काउन्सिल (एनएमसी) ले सार्वजनिक गरेको चिकित्सक दर्ता प्रमाणपत्र (लाइसेन्स) परीक्षा  जेठ १२ देखि १५ गतेसम्म सञ्चालन गरिएको थियो । ६९औँ चिकित्सक लाइसेन्स परीक्षामा यसवर्ष दुई हजार २६३ परीक्षार्थी परीक्षामा सामेल भएकामध्ये एक हजार ५१५ जना मात्र उत्तीर्ण भएका हुन् । नेपाल मेडिकल काउन्सिलले नेपाली मेडिकल कलेजबाट अध्ययन गरेका विद्यार्थीको उत्तीर्ण दर उल्लेखनीय भएको जनाएको छ । विदेशबाट अध्ययन गरी फर्किएका अधिकांश परीक्षार्थी अनुत्तीर्ण भएको काउन्सिलका निमित्त रजिष्ट्रार डा दीपेन्द्र पाण्डेले बताए ।\nएमबीबीएसतर्फ नेपालका मेडिकल कलेजबाट सहभागी एक हजार २५४ परीक्षार्थीमध्ये ९६३ जना अर्थात् ७६ दशमलव ७९ प्रतिशत उत्तीर्ण भएका छन् ।\nचीनबाट अध्ययन गरी आएका १३३ मध्ये २० जना अर्थात् १५ दशमलव ०४ प्रतिशत  बङ्गलादेशबाट अध्ययन गरेका ३६७ जनामध्ये १५१ जना अर्थात् ४१ दशमलव १४ प्रतिशत, भारतबाट एमबीबीएस अध्ययन गरेका परीक्षार्थीको उत्तीर्ण प्रतिशत ४२ दशमलव ३१  छ भने फिलिपिन्सबाट अध्ययन गरेका परीक्षार्थीमध्ये २८ दशमलव ५७ प्रतिशत  सफल भएका छन् ।\nइजिप्ट, कीर्गिस्तान, रुस तथा युक्रेनबाट अध्ययन गरी आएका परीक्षार्थीमध्ये यसपटक कोही उत्तीर्ण हुन सकेनन् । बीडीएसतर्फ स्वदेशी कलेजकै नतिजा उत्कृष्ट देखिएको छ । नेपालका कलेजबाट सहभागी ४०० परीक्षार्थीमध्ये ३४३ जना अर्थात् ८५ दशमलव ७५ प्रतिशत उत्तीर्ण भएका छन् । भारतबाट बिडिएस अध्ययन गरी आएका १७ मध्ये एक जना मात्रै सफल भएका छन् ।\nनतिजाअनुसार एमबीबीएसतर्फ चितवन मेडिकल कलेज ९३ दशमलव १० प्रतिशत नतिजासहित उत्कृष्ट बनेको छ भने बिपी कोइराला स्वास्थ्य विज्ञान प्रतिष्ठानका ९२ दशमलव २१ प्रतिशत तथा नेपाली सेना स्वास्थ्य विज्ञान संस्थानका ९१ दशमलव ६७ प्रतिशत विद्यार्थी उत्तीर्ण भएका छन् । बिडिएसतर्फ गण्डकी मेडिकल कलेजका शतप्रतिशत विद्यार्थी सफल भएका छन् ।\nविदेशबाट अध्ययन गरी आएका परीक्षार्थीको नतिजा कमजोर आउनुको मुख्य कारण भाषागत अवरोध तथा पाठ्यक्रमको भिन्नता रहेको काउन्सिलका निमित्त रजिष्ट्रार डा पाण्डेले बताए',
 'कोरला नाकाबाट भित्रिएका ७७४ विद्युतीय गाडी भन्सार छलीको आशंकामा सशस्त्रको नियन्त्रणमा | BAJARKO CHIRFAR': 'सशस्त्र प्रहरी बल नेपालले भन्सार छलेको आशङ्कामा मुस्ताङको कोरोला नाकाबाट भित्रिएका ७७४ वटा विद्युतीय सवारीसाधन नियन्त्रणमा लिएको छ ।\nमुस्ताङको जोमसोम, पर्वतको कुस्मा र कास्कीको हेम्जाबाट गएराति ती गाडी नियन्त्रणमा लिइएको सशस्त्र प्रहरी बलका प्रवक्ता विष्णुप्रसाद भट्टले जानकारी दिए ।\nगाडी नियन्त्रणमा लिन सशस्त्र प्रहरी बल नेपाल नं ३३ गुल्म मुस्ताङ, म्याग्दी गुल्म, नं २५ चण्डिका गण पर्वत, नं २४ कालिका गण कास्कीबाट  सुरक्षाकर्मी परिचालन भएका थिए ।\nयसैगरी, नुवाकोटको पासाङल्हामु सडकबाट पनि दुई वटा गाडी नियन्त्रणमा लिइएको छ ।',
 'प्रधानमन्त्रीको प्रचारपछि बढ्यो डीडीसी उत्पादनको माग: दूध, दही, घिउ र पनिरको मूल्य बढ्यो | BAJARKO CHIRFAR': 'सरकारी स्वामित्वको दुग्ध विकास संस्थान (डीडीसी) ले आफ्ना केही दुग्धजन्य उत्पादनको मूल्य बढाएको छ। बजारमा माग बढेको भन्दै संस्थानले दूध, दही, घिउ र पनिरको मूल्य समायोजन गरेको हो।\nडीडीसीका अनुसार आधा लिटर दूधको मूल्य ४९ रुपैयाँबाट ५० रुपैयाँ पुर्\u200dयाइएको छ। प्रतिलिटर दहीको मूल्य १५० रुपैयाँबाट १६० रुपैयाँ पुगेको छ भने २०० ग्राम दहीको मूल्य ४० रुपैयाँबाट ४५ रुपैयाँ बनाइएको छ। आधा लिटर बट्टावाला दहीको मूल्य ८० रुपैयाँबाट ८५ रुपैयाँ पुगेको छ।\nत्यस्तै, घिउको मूल्य प्रतिलिटर १०० रुपैयाँले बढाएर १,२५० रुपैयाँ कायम गरिएको छ। पनिरको मूल्य प्रतिकिलो ८२५ रुपैयाँबाट ८७५ रुपैयाँ पुर्\u200dयाइएको छ।',
 'नेपालको पासपोर्ट र्याङ्किङमा सुधार, कति औं स्थानमा पुग्यो ? | BAJARKO CHIRFAR': 'नेपालले हेन्ली पासपोर्ट इन्डेक्स–२०२६ मा चार स्थान सुधार गर्दै आफ्नो स्थिति उकालेको छ। नयाँ प्रतिवेदनअनुसार नेपाल १०१औं स्थानबाट ९७औं स्थानमा पुगेको हो। नेपालले उत्तर कोरियासँग ९७औं स्थान साझा गरेको छ, जहाँ दुवै देशको भिसा–फ्री स्कोर ३५ रहेको छ।\nइन्डेक्सअनुसार सिंगापुर शीर्ष स्थानमा रहेको छ, जसका नागरिकले १९२ देशमा भिसा–फ्री पहुँच पाएका छन्। दोस्रो स्थानमा जापान, दक्षिण कोरिया र संयुक्त अरब इमिरेट्स (यूएई) रहेका छन् भने तेस्रो स्थानमा स्विडेन रहेको छ।\nचौथो स्थानमा बेल्जियम, डेनमार्क, फिनल्यान्ड, फ्रान्स, जर्मनी, आयरल्यान्ड, इटाली, लक्जम्बर्ग, नेदरल्यान्ड, नर्वे, स्पेन र स्विट्जरल्यान्ड परेका छन्। पाँचौं स्थानमा अस्ट्रिया, ग्रिस, माल्टा र पोर्चुगल रहेका छन्।\nप्रतिवेदनअनुसार सन् २०२५ मा शीर्ष १० बाट बाहिरिएको अमेरिका पुनः शीर्ष १० भित्र फर्किएको छ। दक्षिण एसियाली देशहरूमा भारत ७८औं स्थानमा छ भने चीन ५६औं स्थानमा पुगेको छ। पाकिस्तान १००औं स्थानमा रहँदा अफगानिस्तान सूचीको अन्तिम स्थानमा रहेको छ।'}

In [25]:
import datetime

In [32]:
from datetime import datetime

now = datetime.now()
news_time=str(now).replace(" ","_")

'2026-06-04_16:40:17.639989'

In [37]:
df['title']

0    टिकटकर तुलसा अधिकारी पुर्पक्षका लागि जेल चलान ...
1    चिकित्सक लाइसेन्स परीक्षामा स्वदेशी कलेज अग्रस...
2    कोरला नाकाबाट भित्रिएका ७७४ विद्युतीय गाडी भन्...
3    प्रधानमन्त्रीको प्रचारपछि बढ्यो डीडीसी उत्पादन...
Name: title, dtype: object

In [40]:
df['news'][0]

'ललितपुर जिल्ला अदालतले तुल्सा अधिकारीलाई पुर्पक्षका लागि थुनामा पठाउन आदेश दिएको छ। जिल्ला अदालत ललितपुरका न्यायाधीश टेकनाथ गौतमको इजलासले यस्तो आदेश दिएको हो।\nअधिकारीविरुद्ध जिल्ला सरकारी वकिल कार्यालयले आपराधिक लाभ (एक्सटर्सन), संगठित अपराध र सम्पत्ति शुद्धीकरण (मनी लाउण्डरिङ) कसुरमा अदालतमा मुद्दा दर्ता गरेको थियो ।\nलामो समयदेखि फरार रहेकी उनलाई हालै पक्राउ गरिएको हो। गत शनिबार थाइल्यान्डबाट पक्राउ गरी नेपाल ल्याइएको उनलाई सोमबार अदालतमा उपस्थित गराइएको थियो।'

In [44]:
now = datetime.now()
news_time=str(now).replace(" ","_")    
news_time[:-10]

'2026-06-04_16:50'

In [51]:
!pip install gspread google-auth gspread-dataframe

Collecting gspread
  Downloading gspread-6.2.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: google-auth in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (2.49.1)
Collecting gspread-dataframe
  Downloading gspread_dataframe-4.0.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting google-auth-oauthlib>=0.4.1 (from gspread)
  Downloading google_auth_oauthlib-1.4.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from google-auth) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from google-auth) (48.0.0)
Requirement already satisfied: pandas>=0.24.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from gspread-dataframe) (2.2.3)
Requirement already satisfied: six>=1.12.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from gspread-dataframe) (1.16.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from cryptography>=38.0.3->google-auth) (2.0.0)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.4.1->gspread)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.24.0->gspread-dataframe) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.24.0->gspread-dataframe) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.24.0->gspread-dataframe) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.24.0->gspread-dataframe) (2024.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.6.2)
Requirement already satisfied: pycparser in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth) (2.22)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: requests>=2.0.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2024.8.30)
Downloading gspread-6.2.1-py3-none-any.whl (59 kB)
Downloading gspread_dataframe-4.0.0-py2.py3-none-any.whl (9.0 kB)
Downloading google_auth_oauthlib-1.4.0-py3-none-any.whl (19 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
Installing collected packages: oauthlib, requests-oauthlib, google-auth-oauthlib, gspread, gspread-dataframe
Successfully installed google-auth-oauthlib-1.4.0 gspread-6.2.1 gspread-dataframe-4.0.0 oauthlib-3.3.1 requests-oauthlib-2.0.0

WARNING: Ignoring invalid distribution ~treamlit (C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [54]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\data_extractions\\api_datasets'